apiVersion: microcks.github.io/v1alpha1
kind: MicrocksInstall
metadata:
  name: bm
spec:
  features:
    async: 
      kafka:
        url: mercury-kafka-kafka-bootstrap:9092
  keycloak:
    url: keycloak-mercury-infra.apps.mw-ocp4.cloud.lab.eng.bos.redhat.com
    privateUrl: http://keycloak-discovery.mercury-infra.svc.cluster.local:8443/auth