apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../namespace
 - ../../../base/keycloak
# TODO: Refactor
commonLabels:
  app: mercury
  mercury: infra
  mercury-infra: keycloak
namespace: mercury-infra