apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - subscription.yaml
  - keycloak.yaml
  - realm.yaml
  - users.yaml
commonLabels:
  app: mercury
  mercury: infra
  mercury-infra: keycloak
namespace: mercury-infra