apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microcks
spec:
  project: default
  source:
    repoURL: https://github.com/ruromero/mercury-env.git
    targetRevision: HEAD
    path: mercury-infra/microcks
  destination:
    server: https://kubernetes.default.svc
    namespace: mercury-infra