apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apicurito
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/ruromero/mercury-env.git
    targetRevision: HEAD
    path: mercury-infra/base/apicurito
  destination:
    server: https://kubernetes.default.svc
    namespace: mercury-infra