apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../../../base/apicurio-registry
patchesStrategicMerge:
  - patches/apicurio-registry.yaml
# TODO: Refactor
commonLabels:
  app: mercury
  mercury: infra
  mercury-infra: apicurio-registry
namespace: mercury-infra