apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    operators.coreos.com/keycloak-operator.mercury-infra: ""    
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: keycloak-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: keycloak-operator.v15.0.2