apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: mercury-admin
spec:
  user:
    username: admin
    firstName: Admin
    lastName: Istrator
    enabled: True
    credentials:
      - type: password
        value: RedHat1!
    realmRoles:
      - offline_access
      - uma_authorization
      - admin
    clientRoles:
      account:
        - manage-account
        - view-profile
      realm-management:
        - manage-users
        - view-users
        - query-users
        - create-client
  realmSelector:
    matchLabels:
      app: mercury
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: mercury-bernie
spec:
  user:
    username: bernie
    firstName: Bernard
    lastName: Bernoulli
    enabled: True
    credentials:
      - type: password
        value: purple
    realmRoles:
      - user
      - analyst
      - developer
  realmSelector:
    matchLabels:
      app: mercury
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: mercury-pepe
spec:
  user:
    username: pepe
    firstName: Jose
    lastName: Dominguez
    enabled: True
    credentials:
      - type: password
        value: calatrava
    realmRoles:
      - marketing
  realmSelector:
    matchLabels:
      app: mercury