apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../../../base/microcks
patchesStrategicMerge:
  - patches/microcks.yaml
  - patches/keycloak-clients.yaml
# TODO: Refactor
commonLabels:
  app: mercury
  mercury: infra
  mercury-infra: microcks
namespace: mercury-infra