apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mercury-kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      inter.broker.protocol.version: "2.7"
      log.message.format.version: "2.7"
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
    - name: tls
      port: 9093
      tls: true
      authentication:
        type: tls
      type: internal
    - name: external
      port: 9094
      tls: true
      type: route
      authentication:
        type: tls
    authorization:
      type: simple
    replicas: 1
    storage:
      type: jbod
      volumes:
      - id: 0
        size: 10Gi
        type: persistent-claim
    version: 2.7.0
  zookeeper:
    replicas: 1
    storage:
      size: 10Gi
      type: persistent-claim