apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: microcks
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: microcks
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: microcks-operator.v1.3.0