apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: bian-argo
  namespace: mercury-infra
  labels:
    app: mercury
spec:
  image: quay.io/argoproj/argocd
  server:
    route: 
      enabled: true
  redis:
    image: quay.io/ruben/redis
    version: 6.2.4-alpine
  dex:
    openShiftOAuth: true
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
      g, syseng-mw-users, role:admin
    scopes: '[groups]'