apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-subscription-rolebinding
  namespace: mercury-infra
subjects:
- kind: ServiceAccount
  name: bian-argo-argocd-application-controller
- kind: ServiceAccount
  name: bian-argo-argocd-server
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io